-- Create table for Water Previsions (Budget / Charges)
create table public.water_previsions (
  id bigint generated by default as identity primary key,
  lot_id bigint references public.lots(id) not null,
  year int not null,
  quarter text not null, -- 'T1', 'T2', 'T3', 'T4'
  amount_sub numeric default 0,
  amount_conso numeric default 0,
  amount_regul numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (lot_id, year, quarter)
);

-- RLS Policies
alter table public.water_previsions enable row level security;

create policy "Enable read access for authenticated users"
on public.water_previsions for select
to authenticated
using (true);

create policy "Enable insert/update for authenticated users"
on public.water_previsions for all
to authenticated
using (true)
with check (true);
