-- Create tables for Monthly Budget Data (Dépenses Prévisionnelles & Trésorerie)
-- These tables persist the data from BudgetDetailTab (onglet "5. Détail & Trésorerie")

-- ============================================================================
-- TABLE 1: monthly_expenses
-- Stores monthly expense amounts per budget item
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.monthly_expenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_item_id integer REFERENCES public.budget_items(id) ON DELETE CASCADE NOT NULL,
    year integer NOT NULL,
    month integer NOT NULL CHECK (month >= 1 AND month <= 12),
    amount numeric(12,2) DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (budget_item_id, year, month)
);

ALTER TABLE public.monthly_expenses OWNER TO postgres;

COMMENT ON TABLE public.monthly_expenses IS 'Dépenses prévisionnelles mensuelles par poste budgétaire';
COMMENT ON COLUMN public.monthly_expenses.budget_item_id IS 'Référence vers le poste budgétaire (budget_items)';
COMMENT ON COLUMN public.monthly_expenses.month IS 'Mois (1=Janvier, 12=Décembre)';
COMMENT ON COLUMN public.monthly_expenses.amount IS 'Montant prévu pour ce mois';

-- ============================================================================
-- TABLE 2: monthly_income
-- Stores monthly income/treasury data (Recettes / Trésorerie)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.monthly_income (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year integer NOT NULL,
    month integer NOT NULL CHECK (month >= 1 AND month <= 12),
    calls_amount numeric(12,2) DEFAULT 0,      -- Appels de Fonds
    reguls_amount numeric(12,2) DEFAULT 0,     -- Régularisation Charges
    other_amount numeric(12,2) DEFAULT 0,      -- Autres Produits
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (year, month)
);

ALTER TABLE public.monthly_income OWNER TO postgres;

COMMENT ON TABLE public.monthly_income IS 'Recettes et trésorerie mensuelles';
COMMENT ON COLUMN public.monthly_income.calls_amount IS 'Montant des appels de fonds';
COMMENT ON COLUMN public.monthly_income.reguls_amount IS 'Montant des régularisations de charges';
COMMENT ON COLUMN public.monthly_income.other_amount IS 'Autres produits';

-- ============================================================================
-- INDEXES for performance
-- ============================================================================
CREATE INDEX idx_monthly_expenses_year ON public.monthly_expenses(year);
CREATE INDEX idx_monthly_expenses_budget_item ON public.monthly_expenses(budget_item_id);
CREATE INDEX idx_monthly_income_year ON public.monthly_income(year);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================
ALTER TABLE public.monthly_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_income ENABLE ROW LEVEL SECURITY;

-- monthly_expenses policies
CREATE POLICY "Authenticated users can read monthly_expenses"
ON public.monthly_expenses FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated users can manage monthly_expenses"
ON public.monthly_expenses FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- monthly_income policies
CREATE POLICY "Authenticated users can read monthly_income"
ON public.monthly_income FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated users can manage monthly_income"
ON public.monthly_income FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- ============================================================================
-- GRANTS
-- ============================================================================
GRANT ALL ON TABLE public.monthly_expenses TO anon;
GRANT ALL ON TABLE public.monthly_expenses TO authenticated;
GRANT ALL ON TABLE public.monthly_expenses TO service_role;

GRANT ALL ON TABLE public.monthly_income TO anon;
GRANT ALL ON TABLE public.monthly_income TO authenticated;
GRANT ALL ON TABLE public.monthly_income TO service_role;

GRANT ALL ON SEQUENCE public.monthly_expenses_id_seq TO anon;
GRANT ALL ON SEQUENCE public.monthly_expenses_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.monthly_expenses_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.monthly_income_id_seq TO anon;
GRANT ALL ON SEQUENCE public.monthly_income_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.monthly_income_id_seq TO service_role;
